### ISSUE TITLE
Update for Catalina 

### ISSUE THREAD

**Issue by sandrophoto** [w0lfschild/Flashlight#65] opened 2019-11-04 10:29 UTC
Hello, sadly this stopped to work after Catalina install :(
Is it planned to update Flashlight for Catalina ?
I hope so.

Thank you sooo much for this.

**Comment by w0lfschild** [comment] 2019-11-14 05:11
Yeah I looked into it a bit. Didn't see any easy fix but I could be misguided.

If someone else manages to fix it I'll gladly merge a PR and push out an update though.

Since this project seems to still be fairly popular **_I'll throw a $25 bounty on this issue_**.

**Comment by xyjigsaw** [comment] 2019-11-28 13:04
I wanna try it.
Wound mind teach me how to import this to Xcode?

**Comment by w0lfschild** [comment] 2019-11-28 17:25
@xyjigsaw 

I'm afraid that if you don't know how to download and open a project in Xcode it might be a lost cause to bother trying. Regardless here's how to open the project.

On the repo main page click clone or download and download a zip of the project. Then open up Flashlight.xcworkspace

The plugin scheme is called SpotlightSIMBL.

**Comment by WilixLead** [comment] 2019-11-28 17:41
It requires any changes in SDK usage or in permission requests or it just related to recompile to latest kernel version?
PS: Flashlight still require disabling SIP ?

**Comment by w0lfschild** [comment] 2019-11-28 18:04
@WilixLead 

Erm wouldn't say it's exactly SDK usage. More like changes have been made to Spotlight that break compatibility. So most likely either class names or implementation of something has changed. This would require some level of reverse engineering and or knowledge of Objective-c

Here's the headers of the latest version of Spotlight: https://github.com/w0lfschild/macOS_headers/tree/master/macOS/CoreServices/Spotlight/2075.4

Yes Flashlight does require SIP be disabled.

I've also posted this bounty on reddit and bumped the reward to $25:
https://www.reddit.com/r/TweakBounty/comments/dze7xw/1501015macos_icon_theming/
https://www.reddit.com/r/OSXTweaks/comments/dxcv9j/tweak_bounty/

**Comment by WilixLead** [comment] 2019-12-25 22:22
I start research this problem. So I found this line
`osascript -e 'tell application \"Spotlight\" to inject SIMBL into Snow Leopard'`
This command return code -2740 in my system. As I understand we need inject SIMBL bundle to Spotlight process but now in throws error. I don't find any other places in Flashlight where this bundle can be loaded. I think we need fix this AppleScript for success injecting.

I am not an macOS or Objective-C developer and don't know AppleScript :)
@w0lfschild this problem can be related for old headers for SIMBL subproject?  (if yes, I try update headers. But currently, all project builds fine)

PS: Code try to find path `/Library/Application Support/SIMBL/Plugins/SpotlightSIMBL.bundle` and I don't have this one in my mac, but I think it should be created after SIMBL injecting

**Comment by w0lfschild** [comment] 2019-12-27 21:23
@WilixLead 

The issue is not loading the bundle. You can use MacForge for that.

**Comment by WilixLead** [comment] 2019-12-28 13:04
> @WilixLead
> 
> The issue is not loading the bundle. You can use MacForge for that.

Has any way for load this bundle without MacForge? For make Flashlight independent from MacForge

**Comment by w0lfschild** [comment] 2019-12-28 22:43
@WilixLead 

Flashlight has always required a loader. Also as I said above that doesn't have anything to do with it not working on Catalina.

**Comment by WilixLead** [comment] 2019-12-28 22:47
@w0lfschild Yea... I already got it. May be you can say few words about how I can connect to injected bundle for debugging? :)

PS: I already inject Flashlight and Spotlight now crush. I try attach debugger to Spotlight after injecting bundle and Spotlight always throws ACCESS error exception. So I just see ASM code.

**Comment by w0lfschild** [comment] 2019-12-31 21:38
Resolved in : https://github.com/w0lfschild/Flashlight/pull/66

Update will be out soon.

**Closed as completed by w0lfschild** 2019-12-31 21:38 UTC
Labels: bug, help wanted
